name: '[auto-run-jupyter]'

on: push

    # ignore changes to to ipynb
    # this is mainly to prevent cyclic reruns
    # paths-ignore:
    # - '**.ipynb'

jobs:
  clear-and-run:
    runs-on: ubuntu-latest
    env:
      JUGEX_REFRESH_TOKEN: ${{ secrets.JUGEX_REFRESH_TOKEN }}
      JUGEX_CLIENT_ID: ${{ secrets.JUGEX_CLIENT_ID }}
      JUGEX_CLIENT_SECRET: ${{ secrets.JUGEX_CLIENT_SECRET }}
      HBP_OIDC_ENDPOINT: ${{ secrets.HBP_OIDC_ENDPOINT }}
      PYTHON_VERSION: '3.6' # run on lowest requirement

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U .
    - name: Clear all outputs
      run: |
        for file in $(find ./docs -type f -name *.ipynb); do
          jupyter nbconvert --clear-output --inplace $file
        done
    - name: Generate new outputs
      run: |
        for file in $(find ./docs -type f -name *.ipynb); do
          echo "---- Testing execurtion of ${nbfile} ----"
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 \
            --output /tmp/nbtest.ipynb ${nbfile}
        done
    - name: Commit to this branch
      run: |
        git config --global user.name 'Xiao Gui'
        git config --global user.email 'xgui3783@gmail.com'
        git commit -am "[skip ci] Update"
        git push